dex_api_url: "https://api.dexscreener.com/latest/dex/tokens/"
rugcheck_api_url: "https://api.rugcheck.xyz/v1/token-analysis"
database_url: "postgresql://user:password@localhost/dexscreener"
telegram_bot_token: "your_telegram_bot_token"
telegram_chat_id: "your_telegram_chat_id"
bonkbot_command_prefix: "/bonkbot"

filters:
  min_liquidity: 10000  # Minimum liquidity in USD
  max_price_change: 50  # Maximum 24h price change in percentage
  fake_volume_threshold: 0.7  # Maximum allowed fake volume ratio (0.7 = 70%)

blacklist:
  coins:
    - "0xRugPullToken1"
    - "0xRugPullToken2"
  devs:
    - "0xRugPullDev1"
    - "0xRugPullDev2"
